platform :ios, '8.0'

pod 'AFNetworking', '~> 2.5'
pod 'Ono', '~> 1.2'
pod 'AFOnoResponseSerializer', '~> 1.0'
pod 'SpinKit', '~> 1.2'
pod 'MBProgressHUD', '~> 0.9'
pod 'DZNEmptyDataSet', '~> 1.5'
pod 'CocoaLumberjack', '2.0.0-rc'
pod 'TTTLocalizedPluralString', '~> 0.0'